# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Welcome to Qianqian's World
email: qianqian.zhu@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, welcome to Qianqian's World.
  I am a PhD candidate in Software Engineering at TU Delft.
  Keep calm and carry on. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://qianqianzhu.github.io" # the base hostname & protocol for your site
twitter_username: cuteqianqianzhu
github_username:  qianqianzhu

# Build settings
markdown: kramdown
